// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ9MNZzPP9_pNvBlDBwx7Sc_vOLokC8Gs',
    appId: '1:831173094264:web:304d22feb41ed419d9768d',
    messagingSenderId: '831173094264',
    projectId: 'flutter-cd-9a3e1',
    authDomain: 'flutter-cd-9a3e1.firebaseapp.com',
    storageBucket: 'flutter-cd-9a3e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjAdwjeXm_F46KqqEoAKkSuT37zyC8hI',
    appId: '1:831173094264:android:eb8f3adbc7949932d9768d',
    messagingSenderId: '831173094264',
    projectId: 'flutter-cd-9a3e1',
    storageBucket: 'flutter-cd-9a3e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qLu71PexWApLPTEzxzqDlgsnu0oej6c',
    appId: '1:831173094264:ios:e61f0d6a1227038cd9768d',
    messagingSenderId: '831173094264',
    projectId: 'flutter-cd-9a3e1',
    storageBucket: 'flutter-cd-9a3e1.appspot.com',
    iosClientId: '831173094264-361qld90g42g5sc2dffu3skvjahj3ajf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4qLu71PexWApLPTEzxzqDlgsnu0oej6c',
    appId: '1:831173094264:ios:e61f0d6a1227038cd9768d',
    messagingSenderId: '831173094264',
    projectId: 'flutter-cd-9a3e1',
    storageBucket: 'flutter-cd-9a3e1.appspot.com',
    iosClientId: '831173094264-361qld90g42g5sc2dffu3skvjahj3ajf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefire',
  );
}
